### ISSUE TITLE
Request: Suggestion

### ISSUE THREAD

**Issue by Adam1609** [NL-4-DEVS/PocketRPG#20]
Adding more health and more damage base on experience level, and could u add enchant support on each class?

**Comment by Sandertv** [comment]
Yeah the more health and damage I'm definitely going to add, I had that in mind too. Enchant support I don't really know, I'm not sure if enchantments would work or not on the weapons.

**Comment by Sandertv** [comment]
I'm going to add this in the 0.4 update. Will be the first on my list to do :)

**Comment by Sandertv** [comment]
Okay more damage per level is added :)

**Comment by Adam1609** [comment]
Next Suggestion: Custom Enchantment (maybe?)

**Comment by Adam1609** [comment]
Sorry for spamming but, missing more health per level yah!

**Comment by Sandertv** [comment]
Yeah health per level will be added soon, custom enchants I'll keep in mind.

**Comment by Adam1609** [comment]
Your plugin is great for mmoRPG like server :D

**Comment by Sandertv** [comment]
It's what I made it for :) I originally made it for my own server, but I thought it'd be nice if others could profit too :)

**Comment by Adam1609** [comment]
Adding the plugin, my server's member love it, but too much damage will cause one hit, so I recommend to add more health on level

**Comment by Sandertv** [comment]
Yep! Going to add that next, new abilities after!

**Comment by Adam1609** [comment]
You are the only one who could do this, even though!

**Comment by Sandertv** [comment]
Health per level added :)

**Comment by Adam1609** [comment]
I wish I could help you, but all the bug i have make a PR :D

**Comment by Sandertv** [comment]
You already help me a lot by reporting bugs though! :)

**Comment by Adam1609** [comment]
I was free on today, and I am thinking about your plugin though!

**Comment by Sandertv** [comment]
Okay both health and damage have a scailing of 0.2 per level, which would mean 2 health on level 10 and 2 more damage when hitting an enemy. (both only in RPG world) At level 30 this would mean you can kill any non-armored entity with 2 hits. (or less of course) Tell me if this amount is okay, or if it should be lowered @Adam1609 :)

**Comment by Adam1609** [comment]
Okay, I would think about the entity monster spawn at night though

**Comment by Adam1609** [comment]
[16:54:35] [Server thread/CRITICAL]: ParseError: "syntax error, unexpected 'public' (T_PUBLIC)" (EXCEPTION) in "/plugins/RPG_raw/src/PocketRPG/Main" at line 74
wow, I looked at it though

**Comment by Sandertv** [comment]
Fixed.

**Comment by Adam1609** [comment]
I think i have a suggestion:
Because members like to change class everytime, we need to have a "quit" command, and clear all RPG items. And also confirm as well

**Comment by Sandertv** [comment]
We're working on the quit command right now, it will be added in a new update soon. Confirm for choosing will be added too.

**Comment by Adam1609** [comment]
[13:30:01] [Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerExperienceChangeEvent' to 'PocketRPG v0.3.0': Call to undefined method pocketmine\Player::getFilledXp() on PocketRPG\eventlistener\EventListener
[13:30:01] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\Player::getFilledXp()" (EXCEPTION) in "/plugins/RPG_raw/src/PocketRPG/eventlistener/EventListener" at line 368
next error, I think I am a error reporter or something :)

**Comment by Sandertv** [comment]
Already doubted that function, it's fixed now :) Thanks a lot for testing it!

**Comment by Adam1609** [comment]
Anyway, it's amazing that only you could do this plugin like that, I love RPG and I love this plugin. I have been watching this plugin since starting.

**Comment by Sandertv** [comment]
Yep I'm happy to have people like you to help me with testing and stuff too! :)

**Comment by Adam1609** [comment]
I try that reset command, still don't give any sign of:
[13:41:03] [Server thread/CRITICAL]: Unhandled exception executing command 'rpg reset' in rpg: Call to undefined method pocketmine\Player::getOwner()
[13:41:03] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\Player::getOwner()" (EXCEPTION) in "/plugins/RPG_raw/src/PocketRPG/commands/RpgCommands" at line 126

**Comment by Sandertv** [comment]
Whoops lol, can't get the default level of a $p :P

**Comment by Sandertv** [comment]
Fixed now :)

**Comment by Adam1609** [comment]
[14:19:45] [Server thread/CRITICAL]: ParseError: "syntax error, unexpected '$p' (T_VARIABLE)" (EXCEPTION) in "/plugins/RPG_raw/src/PocketRPG/commands/RpgCommands" at line 130
wait, no touching anything here

**Comment by Sandertv** [comment]
I think I might add events to the api so you can give enchanted items for example on quest finish in a plugin.

**Comment by Sandertv** [comment]
I've added a first event (not sure if it works yet) which gets fired when completing a quest. Would be appreciated if you could test it (and feel free to use it too 😜 )

**Comment by Adam1609** [comment]
At first, I test it, but something causes bug when start quest

**Comment by Adam1609** [comment]
[07:19:14] [Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerExperienceChangeEvent' to 'PocketRPG v0.3.0': Call to undefined method pocketmine\Player::getXp() on PocketRPG\eventlistener\EventListener
[07:19:14] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\Player::getXp()" (EXCEPTION) in "/plugins/RPG_raw/src/PocketRPG/eventlistener/EventListener" at line 374

**Comment by Sandertv** [comment]
Yeah this can be a problem... In newer Genisys versions getXp() is being used while in older ones getExp() is used. I don't know which server software you use but try updating it :)

**Comment by Sandertv** [comment]
I'll change it back to setExp() as clearsky uses this too and it still works on genisys (but gives deprecated error)

**Comment by Sandertv** [comment]
It's changed, try it now!

**Comment by Sandertv** [comment]
Not sire if that was the same error but if it is that is fixed now.

**Comment by Adam1609** [comment]
[11:02:09] [Server thread/CRITICAL]: Unhandled exception executing command 'rpg reset' in rpg: Call to undefined method PocketRPG\Main::clearAllQuests()
[11:02:09] [Server thread/CRITICAL]: Error: "Call to undefined method PocketRPG\Main::clearAllQuests()" (EXCEPTION) in "/plugins/RPG_raw/src/PocketRPG/commands/RpgCommands" at line 123
ClearAllQuest?

**Comment by Sandertv** [comment]
Hmmm I can't find out what the problem is...

**Comment by Adam1609** [comment]
Hey could you add multiworld RPG support :)

**Comment by Sandertv** [comment]
Aure, will be some more work but I can do that!

**Comment by Adam1609** [comment]
My member has a suggestion: Because they love bow and arrow so much, they suggest to have new class: Archer. I will be very happy if you have the class done :)

**Comment by Sandertv** [comment]
I'll add it soon... I can't do a lot about arrows not always hitting perfectly in the server though :/

**Comment by Sandertv** [comment]
I'm working on it.

**Comment by Adam1609** [comment]
Class Chat in Nametag :D my next suggestion!

**Comment by Sandertv** [comment]
Yup I was thinking of this too, will add soon :)

**Comment by oGalatico** [comment]
add class -> Archer 
add skills -> pv(PrivateVaults)
add xp system / + leves 10,20 etc

add Stats :) -> /RPG Stats (skills/xp/level/poder)
                                                                    ↓
                                                          10 [|||||||||||] 11

**Comment by Sandertv** [comment]
Chat system has been finished in the 1.0 update branch, I'm not entirely sure if it works properly with the distance thing, so you'd have to try that out.

**Comment by Sandertv** [comment]
Make sure to let your config.yml regenerate if you do so, it will be needed for the chat to work.

**Comment by Adam1609** [comment]
Oh, archer is finished, so how about some skill? I have some suggestion but I can't describe it as a PHP code. If you played League Of Legend :D

**Comment by Sandertv** [comment]
Might try to add those things, but I do not like the things most plugins use: using a snowball as projectile to damage players. I prefer particles, though it's a whole lot harder to make.

**Comment by Adam1609** [comment]
[10:14:51] [Server thread/CRITICAL]: Unhandled exception executing command 'rpg start worrior' in rpg: Invalid empty level name
[10:14:51] [Server thread/CRITICAL]: pocketmine\utils\LevelException: "Invalid empty level name" (EXCEPTION) in "/src/pocketmine/Server" at line 1162
[10:14:51] [Server thread/CRITICAL]: Unhandled exception executing command 'rpg start warrior' in rpg: Invalid empty level name
[10:14:51] [Server thread/CRITICAL]: pocketmine\utils\LevelException: "Invalid empty level name" (EXCEPTION) in "/src/pocketmine/Server" at line 1162
[10:14:55] [Server thread/INFO]: [CommandTracker] <KietAnh> /say ko đc
[10:14:55] [Server thread/INFO]: ✩Noob»Mє๓๒єгP« KietAnh > ko đc ✩
[10:14:55] [Server thread/INFO]: [CommandTracker] <haipvpvn> /say lai j
[10:14:55] [Server thread/INFO]: ✩Noob»Mє๓๒єгP« haipvpvn > lai j ✩
[10:14:57] [Server thread/CRITICAL]: Unhandled exception executing command 'rpg start mage' in rpg: Invalid empty level name
[10:14:57] [Server thread/CRITICAL]: pocketmine\utils\LevelException: "Invalid empty level name" (EXCEPTION) in "/src/pocketmine/Server" at line 1162
[10:14:58] [Server thread/INFO]: ♫S£rv£r có 3 thể loại: ♫Skywars♫, ♫Guilds♫, ♫Sur-RPG♫
[10:15:02] [Server thread/INFO]: You can only do this in-game
[10:15:08] [Server thread/INFO]: [CommandTracker] <KietAnh> /say lổi
[10:15:08] [Server thread/INFO]: ✩Noob»Mє๓๒єгP« KietAnh > lổi ✩
[10:15:08] [Server thread/CRITICAL]: Unhandled exception executing command 'rpg start worrior' in rpg: Invalid empty level name
[10:15:08] [Server thread/CRITICAL]: pocketmine\utils\LevelException: "Invalid empty level name" (EXCEPTION) in "/src/pocketmine/Server" at line 1162
[10:15:08] [Server thread/CRITICAL]: Unhandled exception executing command 'rpg start warrior' in rpg: Invalid empty level name
[10:15:08] [Server thread/CRITICAL]: pocketmine\utils\LevelException: "Invalid empty level name" (EXCEPTION) in "/src/pocketmine/Server" at line 1162
[10:15:09] [Server thread/CRITICAL]: Unhandled exception executing command 'rpg start worrior' in rpg: Invalid empty level name
[10:15:09] [Server thread/CRITICAL]: pocketmine\utils\LevelException: "Invalid empty level name" (EXCEPTION) in "/src/pocketmine/Server" at line 1162
[10:15:09] [Server thread/CRITICAL]: Unhandled exception executing command 'rpg start warrior' in rpg: Invalid empty level name
[10:15:09] [Server thread/CRITICAL]: pocketmine\utils\LevelException: "Invalid empty level name" (EXCEPTION) in "/src/pocketmine/Server" at line 1162
[10:15:09] [Server thread/CRITICAL]: Unhandled exception executing command 'rpg start worrior' in rpg: Invalid empty level name
[10:15:09] [Server thread/CRITICAL]: pocketmine\utils\LevelException: "Invalid empty level name" (EXCEPTION) in "/src/pocketmine/Server" at line 1162
[10:15:09] [Server thread/CRITICAL]: Unhandled exception executing command 'rpg start warrior' in rpg: Invalid empty level name
[10:15:09] [Server thread/CRITICAL]: pocketmine\utils\LevelException: "Invalid empty level name" (EXCEPTION) in "/src/pocketmine/Server" at line 1162
[10:15:10] [Server thread/CRITICAL]: Unhandled exception executing command 'rpg start tanker' in rpg: Invalid empty level name
[10:15:10] [Server thread/CRITICAL]: pocketmine\utils\LevelException: "Invalid empty level name" (EXCEPTION) in "/src/pocketmine/Server" at line 1162
[10:15:10] [Server thread/INFO]: You can only do this in-game
[10:15:10] [Server thread/CRITICAL]: Unhandled exception executing command 'rpg start mage' in rpg: Invalid empty level name
[10:15:10] [Server thread/CRITICAL]: pocketmine\utils\LevelException: "Invalid empty level name" (EXCEPTION) in "/src/pocketmine/Server" at line 1162
[10:15:10] [Server thread/CRITICAL]: Unhandled exception executing command 'rpg start mage' in rpg: Invalid empty level name
[10:15:10] [Server thread/CRITICAL]: pocketmine\utils\LevelException: "Invalid empty level name" (EXCEPTION) in "/src/pocketmine/Server" at line 1162
[10:15:11] [Server thread/CRITICAL]: Unhandled exception executing command 'rpg start assassin' in rpg: Invalid empty level name
[10:15:11] [Server thread/CRITICAL]: pocketmine\utils\LevelException: "Invalid empty level name" (EXCEPTION) in "/src/pocketmine/Server" at line 1162
[10:15:11] [Server thread/CRITICAL]: Unhandled exception executing command 'rpg start assassin' in rpg: Invalid empty level name
[10:15:11] [Server thread/CRITICAL]: pocketmine\utils\LevelException: "Invalid empty level name" (EXCEPTION) in "/src/pocketmine/Server" at line 1162
this happened in the 1.0 verr

**Comment by Sandertv** [comment]
Make sure to re-add the RPG world in the config :)

**Comment by Adam1609** [comment]
oh I alway forgot @@. And by the way, due to stylish chat, i have to redecorate all :D

**Comment by Sandertv** [comment]
:P

**Comment by Adam1609** [comment]
Oh, it seems that all version has the same bug when message to level 10 give a lot of skill 2's item (spamming)

**Comment by Sandertv** [comment]
Yeah I know it's an annoying bug right now, going to fix it soon.

**Comment by oGalatico** [comment]
Add + level (1-2-3) *- * add Skills plz :)

**Comment by Sandertv** [comment]
Check out the 1.0 update branch, I'm working on a bunch of new abilities/skills

**Comment by Sandertv** [comment]
Found out that the contains() method doesn't work properly with renamed items... This is gonna be a hard one.

**Comment by Adam1609** [comment]
0.16.0 is out, so you must update your plugin to work with Genisys or Phoenix.

**Comment by Sandertv** [comment]
Quite sure it works already.

**Comment by Adam1609** [comment]
Yeah, but for exception, could you help me for memory leak :(( Because when teleporting to another world caused RAM increase all the time
AdvancedKits 5.1 by luca28pet for API(s) 2.0.0
Alias 1.2.0 by ZacHack for API(s) 1.12.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
CommandTracker 1.1 by Scott Handley for API(s) 1.10.0
CoreProtect 0.0.2 by ImagicalGamer for API(s) 1.0.0, 2.0.0, 3.0.0
EconomyAPI 2.0.9 by onebone for API(s) 2.0.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.12.0, 1.13.0, 2.0.0
EconomySell 2.0.7 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.12.0, 1.13.0, 2.0.0
EconomyShop 2.0.7 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.12.0, 1.13.0, 2.0.0
EmptyWorld 1.1.0 by aliuly for API(s) 2.0.0
FuckingSpam 0.1 by BalAnce for API(s) 1.12.0
GMChecker 0.2 by  for API(s) 1.12.0
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
LaunchPads 1.0.0 by MCPEPIG for API(s) 1.0.0
ManyWorlds 2.1.0 by aliuly for API(s) 2.0.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
NetherChests 1.1.1 by aliuly for API(s) 1.12.0
NoDrops 1 by Yupai for API(s) 2.0.0
DevTools 1.1-iTX by PocketMine Team & iTX Technologies LLC for API(s) 2.0.0
PlayerSelector 1 by Ad5001 for API(s) 2.0.0, 1.13.0
PrizeWin 1.0.6 by LilCrispy2o9/Angelo Vidrio for API(s) 1.10.0
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
Sell 2 by Muqsit for API(s) 2.0.0
SimpleAuth 1.7.2 by PocketMine Team, shoghicp for API(s) 2.0.0
SkinChanger 1.2.3 by SalmonDE, Aericio, KairusDarkSeeker for API(s) 2.0.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
VoteReward 3.0.2 by LDX for API(s) 1.12.0, 2.0.0
WorldEdit 1.0.2 by  for API(s) 1.13.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
BuildBattle FleetHD by FleetHD for API(s) 1.0.0, 2.0.0
mcg76_BlockHunt 2.1.0 by minecraftgenius76 for API(s) 1.12.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 2.0.0
FactionsPro 1.3.2 by Array for API(s) 1.14.0, 2.0.0
LevelSystem 1.0.0 by FAMIMA for API(s) 1.0.0, 2.0.0
RedMTag 1 by Skullex for API(s) 1.13.1, 2.0.0, 1.0.0, 1.14.0
REDFeed 1.0BETA by  for API(s) 1.14.0, 2.0.0
REDLagg 0.1 by Adam1609 credit to Sergey_Dertan for API(s) 1.8.0
PocketRPG 0.3.0 by Sandertv for API(s) 2.0.0, 1.13.0
REDFarms 0.0.1 by GlxTeam for API(s) 2.0.0
REDNoBreak 0.1 by Adam1609 for API(s) 2.0.0
RED 0.1 by Adam1609 for API(s) 2.0.0
TradeCraft 0.2 by Jarest (translate and fixable by Adam1609) for API(s) 2.0.0
MyPlot 1 by Wies and Exxarion for API(s) 2.0.0
Here's my list
Make me exception please :) I couldn't fix it

**Comment by Sandertv** [comment]
I think that's a server software issue...

**Comment by Adam1609** [comment]
yeah, or a plugin, maybe?

**Comment by Sandertv** [comment]
I won't update a lot for a couple days, I'm working on fixing EssentialsPE

**Comment by Adam1609** [comment]
Can I test RPG now? I want to make sure to report all and make PRs if possible

**Comment by Sandertv** [comment]
Of course! I'm aware of a bug where /rpg start and /rpg warp are not teleporting you to an RPG world right now.

**Comment by Sandertv** [comment]
Okay most of it works now, the second line of abilities does the job just fine :), you get them when becoming lvl 10.

**Comment by Sandertv** [comment]
Would you mind if I close this issue? It's getting large and laggy, let's talk about this stuff in the gitter chat :)
